### ISSUE TITLE
Create an organization in GHES if the owner of the GitHub.com doesn't exist on the GHES instance

### ISSUE THREAD

**Issue by iheanyi** [actions/actions-sync#1]
Right now, if an organization does not exist on the GHES appliance and we try to sync an action from GitHub.com to the GHES appliance, it will error out with a 404 Not Found since the user or organization does not exist. To remediate this, we can use the GHES API to create an organization with the exact same name as the owner of the GitHub.com repository. Even if the owner of the GitHub.com repository is a regular user and not an organization, we should still create it as an organization since its easier for individual users to create organizations via the API than other user accounts.

**Comment by hashtagchris** [comment]
There isn't a public API to create an organization for GHES. DotCom has [createEnterpriseOrganization](https://docs.github.com/en/graphql/reference/mutations#createenterpriseorganization). If there was a public API there might be some parameters we don't have good defaults for.

We won't be making this enhancement, but https://github.com/actions/actions-sync/pull/9 improves the error message when the organization doesn't exist.

**Comment by hashtagchris** [comment]
I was mistaken, there is a public API for GHES: https://docs.github.com/en/enterprise/2.22/user/rest/reference/enterprise-admin#create-an-organization.
