### ISSUE TITLE
actions-sync tries to create an organization despite the organization existing

### ISSUE THREAD

**Issue by krainboltgreene** [actions/actions-sync#22]
```
error creating github repository `synced-actions/setup-ruby`: error creating organization synced-actions: POST https://example.com/api/v3/admin/organizations: 404 Not Found []
```

**Comment by ajaykn** [comment]
Closing, feel free to reopen, if you are still having the issue :)

**Comment by krainboltgreene** [comment]
I'm working with GES, so I can't create organizations from a token.

**Comment by ajaykn** [comment]
> I'm working with GES, so I can't create organizations from a token.

@krainboltgreene Do you mean GES is GitHub Enterprise Server ?
Trying to understand, why you are not able to create organizations ?
Can you share error message.

> error creating organization synced-actions: POST https://example.com/api/v3/admin/organizations: 404 Not Found []
Apart from that, are you still seeing the error you mentioned in the issue.

**Comment by krainboltgreene** [comment]
@ajaykn Creating orgs in GES requires special permissions that my token doesn't have, and frankly doesn't need. I made the organization ahead of time.

**Comment by ajaykn** [comment]
@krainboltgreene Understand and yeah definitely not needed.
Can you please confirm on one thing.
Are you using 32 bundles or 64 bundles, because we have known issue for 32 bundles.
https://github.com/actions/actions-sync/issues/18

**Comment by ajaykn** [comment]
> Are you using 32 bundles or 64 bundles, because we have known issue for 32 bundles. #18
@krainboltgreene Can you please update

**Comment by ajaykn** [comment]
Closing this and feel free to reopen if the issue still exists.
