### ISSUE TITLE
optional parameter --destination-token?

### ISSUE THREAD

**Issue by ChristophHoyer** [actions/actions-sync#25]
Hej there!
Using the actions-sync I have to add the option --destination-token on the command line. But I don't feel too comfortable typing PATs/passwords on a command line, because they are available in the command history.

Could you think of making this parameter optional? I.e. if it's not provided on the command line, the action-sync command would ask for it in its first step?

**Comment by ajaykn** [comment]
@ChristophHoyer Yeah that makes sense. We will check and see if this can prioritized
