### ISSUE TITLE
Remove requirement on PAT and allow Application Access Token too

### ISSUE THREAD

**Issue by ZauberNerd** [actions/actions-sync#29]
We are running `actions-sync` in a GitHub workflow and are using an application access token instead of a PAT (https://github.com/peter-murray/workflow-application-token-action).
Unfortunately even though the target organization exists, the `actions-sync` fails, because it can't call `client.Users.get()`, because an application cannot access that endpoint (https://github.com/actions/actions-sync/blob/abfafb927f7031b971f51095065abd7d99a6ff13/src/push.go#L127).

Would you accept a PR to alter the `getOrCreateGithubRepo` function (https://github.com/actions/actions-sync/blob/abfafb927f7031b971f51095065abd7d99a6ff13/src/push.go#L118-L162) so that it can work with an application token too (in case the org already exists - otherwise it should fail)?

Related: #14

**Comment by ajaykn** [comment]
> Would you accept a PR to alter the getOrCreateGithubRepo function 

@ZauberNerd Sure, please feel free to post a PR and we are happy to review.
