### ISSUE TITLE
How are checksums calculated

### ISSUE THREAD

**Issue by tuxmanu** [actions/actions-sync#64]
In every release you provide a corresponding gh_202211070205_checksums.txt which includes checksums of each tar.gz file.

But with which algorithm do you calculate them?
COuld you maybe document that in the Readme?

Thanks in advance.

**Comment by ajaykn** [comment]
@tuxmanu We rely internally on go-releaser tool that creates the checksums.
Here is the link that has default values https://goreleaser.com/customization/checksum/

Please let us know if you are looking for any further details.

**Comment by ajaykn** [comment]
Closing and feel free to reopen :)
