### ISSUE TITLE
Scope for fine-grained PAT 

### ISSUE THREAD

**Issue by KittyChiu** [actions/actions-sync#82]
What is the required scope to run `actions-sync` for destination **fine-grained** PAT?

**Comment by younsl** [comment]
In my opinion(I'm not sure though), `actions-sync` doesn't support fine-grained PAT not yet.

## Environment

- AWS EC2 Workload (amd64)
- GHES v3.11.2 ami 2023-12-26 14ec057d89
- GHES Actions Sync v0.2

I already downloaded actions-sync using wget on EC2 local:

```bash
wget https://github.com/actions/actions-sync/releases/download/v202303192358/gh_202303192358_linux_amd64.tar.gz
tar -zxvf gh_202303192358_linux_amd64.tar.gz
```

## Result running `actions-sync` command

My fine-grained PAT include below permissions:

**Contents**: Read and write
**Metadata**: Read-only
**Workflows**: Read and write

Run actions-sync command locally in GHES EC2 instance:

```bash
$ ./actions-sync sync \
  --cache-dir "/tmp/cache" \
  --destination-token "github_pat_11AA..." \
  --destination-url "https://github.<REDACTED>.<REDACTED>" \
  --repo-name actions/setup-node:actions/setup-node
```

It fails with a 401 Bad credentials error:

```bash
fetching * refs for actions/setup-node ...
not using impersonation for the requests
...
error creating github repository `actions/setup-node`: error retrieving authenticated user: GET https://github.<REDACTED>.<REDACTED>/api/v3/user: 401 Bad credentials []
```
