### ISSUE TITLE
Linux amd64 release binary depends on `glibc` version `2.32`

### ISSUE THREAD

**Issue by svasek** [actions/actions-sync#95]
Hello,
The release binary for `linux_amd64` depends on `glibc` version `2.32`. 
This prevent us to run it on Linux distros older then Ubuntu-22.04, RHEL-9, etc. 
When we run it we get the error message: `actions-sync: /lib64/libc.so.6: version 'GLIBC_2.32' not found (required by actions-sync)`

There is a lot of productions systems running older LTS Linux distributions. 
Could you please compile your release binary for older Linux distros?

**Comment by bhundven** [comment]
I also have this issue with self-hosted github action runners in GHES that use LTS 20.04 images.

**Comment by shawnHartsell** [comment]
@svasek @bhundven Thanks for filing an issue, could you let us know what version of `actions-sync` you both are using? I suspect the issue started in https://github.com/actions/actions-sync/releases/tag/v202401161759 when we upgraded the project to Go 1.21. Specifically, I think it's related to https://github.com/golang/go/issues/58550.

I need to look at the source a bit deeper, but I don't think we have any CGO dependencies. We can look into explicitly setting `CGO_ENABLED=0` in our CI build and see if that resolves the issue.

In the meantime, can you revert to the previous release https://github.com/actions/actions-sync/releases/tag/v202303192358 and see if that resolves your issue?

**Comment by bhundven** [comment]
Using that release does work, but I won't get the latest release with #107.

**Comment by svasek** [comment]
Hi, we use [v202303192358](https://github.com/actions/actions-sync/releases/tag/v202303192358) which is the last one which works on Red Hat Enterprise Linux release 8.9. 
It seems the issue was introduced in the release [v202401161759](https://github.com/actions/actions-sync/releases/tag/v202401161759).

**Comment by shawnHartsell** [comment]
Apologies for the delay on this. I've created https://github.com/actions/actions-sync/pull/127 which should resolve the issue. I'll post another reply once we've created a new release so you can test on your systems.

**Comment by svasek** [comment]
Hi @shawnHartsell,
I can confirm the release `v202404231422` works on `Red Hat Enterprise Linux release 8.9` with `GNU libc 2.28`.

Thank you for taking care of this issue.
